version: '3'
services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: demo
      ME_CONFIG_BASICAUTH_PASSWORD: demo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: demo_admin
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: demo_admin
    ports:
      - "27017:27017"
    volumes:
      - ~/demo_app/:/data/db
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge